name: rent_a_car_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #firebase
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  #maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  #state managment
  bloc: ^8.1.4



  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

